/**
 * Comprehensive mapping of city names, countries, states, and timezone aliases
 * to canonical IANA timezone identifiers.
 */

export interface CityInfo {
  name: string;
  country: string;
  timeZone: string;
  flag?: string;
}

export const TARGET_HUBS = [
  {
    name: "London (UK)",
    shortName: "London",
    country: "United Kingdom",
    timeZone: "Europe/London",
    flag: "🇬🇧",
  },
  {
    name: "Tunisia",
    shortName: "Tunisia",
    country: "Tunisia",
    timeZone: "Africa/Tunis",
    flag: "🇹🇳",
  },
  {
    name: "Dhaka (BD)",
    shortName: "Dhaka",
    country: "Bangladesh",
    timeZone: "Asia/Dhaka",
    flag: "🇧🇩",
  },
] as const;

export const CITY_TIMEZONES: Record<string, CityInfo> = {
  // United States & North America
  "chicago": { name: "Chicago", country: "US", timeZone: "America/Chicago" },
  "chi": { name: "Chicago", country: "US", timeZone: "America/Chicago" },
  "new york": { name: "New York", country: "US", timeZone: "America/New_York" },
  "nyc": { name: "New York", country: "US", timeZone: "America/New_York" },
  "ny": { name: "New York", country: "US", timeZone: "America/New_York" },
  "san francisco": { name: "San Francisco", country: "US", timeZone: "America/Los_Angeles" },
  "sf": { name: "San Francisco", country: "US", timeZone: "America/Los_Angeles" },
  "los angeles": { name: "Los Angeles", country: "US", timeZone: "America/Los_Angeles" },
  "la": { name: "Los Angeles", country: "US", timeZone: "America/Los_Angeles" },
  "seattle": { name: "Seattle", country: "US", timeZone: "America/Los_Angeles" },
  "san jose": { name: "San Jose", country: "US", timeZone: "America/Los_Angeles" },
  "san diego": { name: "San Diego", country: "US", timeZone: "America/Los_Angeles" },
  "portland": { name: "Portland", country: "US", timeZone: "America/Los_Angeles" },
  "austin": { name: "Austin", country: "US", timeZone: "America/Chicago" },
  "dallas": { name: "Dallas", country: "US", timeZone: "America/Chicago" },
  "houston": { name: "Houston", country: "US", timeZone: "America/Chicago" },
  "miami": { name: "Miami", country: "US", timeZone: "America/New_York" },
  "boston": { name: "Boston", country: "US", timeZone: "America/New_York" },
  "washington": { name: "Washington DC", country: "US", timeZone: "America/New_York" },
  "dc": { name: "Washington DC", country: "US", timeZone: "America/New_York" },
  "atlanta": { name: "Atlanta", country: "US", timeZone: "America/New_York" },
  "denver": { name: "Denver", country: "US", timeZone: "America/Denver" },
  "phoenix": { name: "Phoenix", country: "US", timeZone: "America/Phoenix" },
  "detroit": { name: "Detroit", country: "US", timeZone: "America/Detroit" },
  "philadelphia": { name: "Philadelphia", country: "US", timeZone: "America/New_York" },
  "minneapolis": { name: "Minneapolis", country: "US", timeZone: "America/Chicago" },
  "cambridge": { name: "Cambridge", country: "UK", timeZone: "Europe/London" },
  "cambridge uk": { name: "Cambridge", country: "UK", timeZone: "Europe/London" },
  "cambridge ma": { name: "Cambridge (MA)", country: "US", timeZone: "America/New_York" },
  "toronto": { name: "Toronto", country: "CA", timeZone: "America/Toronto" },
  "montreal": { name: "Montreal", country: "CA", timeZone: "America/Toronto" },
  "vancouver": { name: "Vancouver", country: "CA", timeZone: "America/Vancouver" },
  "calgary": { name: "Calgary", country: "CA", timeZone: "America/Edmonton" },
  "mexico city": { name: "Mexico City", country: "MX", timeZone: "America/Mexico_City" },
  "honolulu": { name: "Honolulu", country: "US", timeZone: "Pacific/Honolulu" },
  "hawaii": { name: "Hawaii", country: "US", timeZone: "Pacific/Honolulu" },
  "anchorage": { name: "Anchorage", country: "US", timeZone: "America/Anchorage" },

  // UK & Europe
  "london": { name: "London", country: "UK", timeZone: "Europe/London" },
  "ldn": { name: "London", country: "UK", timeZone: "Europe/London" },
  "uk": { name: "London", country: "UK", timeZone: "Europe/London" },
  "manchester": { name: "Manchester", country: "UK", timeZone: "Europe/London" },
  "edinburgh": { name: "Edinburgh", country: "UK", timeZone: "Europe/London" },
  "dublin": { name: "Dublin", country: "IE", timeZone: "Europe/Dublin" },
  "paris": { name: "Paris", country: "FR", timeZone: "Europe/Paris" },
  "berlin": { name: "Berlin", country: "DE", timeZone: "Europe/Berlin" },
  "frankfurt": { name: "Frankfurt", country: "DE", timeZone: "Europe/Berlin" },
  "munich": { name: "Munich", country: "DE", timeZone: "Europe/Berlin" },
  "amsterdam": { name: "Amsterdam", country: "NL", timeZone: "Europe/Amsterdam" },
  "brussels": { name: "Brussels", country: "BE", timeZone: "Europe/Brussels" },
  "madrid": { name: "Madrid", country: "ES", timeZone: "Europe/Madrid" },
  "barcelona": { name: "Barcelona", country: "ES", timeZone: "Europe/Madrid" },
  "rome": { name: "Rome", country: "IT", timeZone: "Europe/Rome" },
  "milan": { name: "Milan", country: "IT", timeZone: "Europe/Rome" },
  "vienna": { name: "Vienna", country: "AT", timeZone: "Europe/Vienna" },
  "zurich": { name: "Zurich", country: "CH", timeZone: "Europe/Zurich" },
  "geneva": { name: "Geneva", country: "CH", timeZone: "Europe/Zurich" },
  "stockholm": { name: "Stockholm", country: "SE", timeZone: "Europe/Stockholm" },
  "oslo": { name: "Oslo", country: "NO", timeZone: "Europe/Oslo" },
  "copenhagen": { name: "Copenhagen", country: "DK", timeZone: "Europe/Copenhagen" },
  "helsinki": { name: "Helsinki", country: "FI", timeZone: "Europe/Helsinki" },
  "warsaw": { name: "Warsaw", country: "PL", timeZone: "Europe/Warsaw" },
  "prague": { name: "Prague", country: "CZ", timeZone: "Europe/Prague" },
  "budapest": { name: "Budapest", country: "HU", timeZone: "Europe/Budapest" },
  "bucharest": { name: "Bucharest", country: "RO", timeZone: "Europe/Bucharest" },
  "athens": { name: "Athens", country: "GR", timeZone: "Europe/Athens" },
  "lisbon": { name: "Lisbon", country: "PT", timeZone: "Europe/Lisbon" },
  "kyiv": { name: "Kyiv", country: "UA", timeZone: "Europe/Kyiv" },
  "istanbul": { name: "Istanbul", country: "TR", timeZone: "Europe/Istanbul" },

  // Africa & Middle East
  "tunis": { name: "Tunis", country: "TN", timeZone: "Africa/Tunis" },
  "tunisia": { name: "Tunisia", country: "TN", timeZone: "Africa/Tunis" },
  "cairo": { name: "Cairo", country: "EG", timeZone: "Africa/Cairo" },
  "casablanca": { name: "Casablanca", country: "MA", timeZone: "Africa/Casablanca" },
  "dubai": { name: "Dubai", country: "AE", timeZone: "Asia/Dubai" },
  "dxb": { name: "Dubai", country: "AE", timeZone: "Asia/Dubai" },
  "uae": { name: "UAE", country: "AE", timeZone: "Asia/Dubai" },
  "abu dhabi": { name: "Abu Dhabi", country: "AE", timeZone: "Asia/Dubai" },
  "riyadh": { name: "Riyadh", country: "SA", timeZone: "Asia/Riyadh" },
  "doha": { name: "Doha", country: "QA", timeZone: "Asia/Qatar" },
  "kuwait": { name: "Kuwait City", country: "KW", timeZone: "Asia/Kuwait" },
  "tel aviv": { name: "Tel Aviv", country: "IL", timeZone: "Asia/Jerusalem" },
  "jerusalem": { name: "Jerusalem", country: "IL", timeZone: "Asia/Jerusalem" },
  "johannesburg": { name: "Johannesburg", country: "ZA", timeZone: "Africa/Johannesburg" },
  "cape town": { name: "Cape Town", country: "ZA", timeZone: "Africa/Johannesburg" },
  "nairobi": { name: "Nairobi", country: "KE", timeZone: "Africa/Nairobi" },
  "lagos": { name: "Lagos", country: "NG", timeZone: "Africa/Lagos" },

  // Asia & Subcontinent
  "dhaka": { name: "Dhaka", country: "BD", timeZone: "Asia/Dhaka" },
  "bd": { name: "Dhaka", country: "BD", timeZone: "Asia/Dhaka" },
  "bangladesh": { name: "Dhaka", country: "BD", timeZone: "Asia/Dhaka" },
  "chittagong": { name: "Chittagong", country: "BD", timeZone: "Asia/Dhaka" },
  "sylhet": { name: "Sylhet", country: "BD", timeZone: "Asia/Dhaka" },
  "delhi": { name: "Delhi", country: "IN", timeZone: "Asia/Kolkata" },
  "new delhi": { name: "New Delhi", country: "IN", timeZone: "Asia/Kolkata" },
  "mumbai": { name: "Mumbai", country: "IN", timeZone: "Asia/Kolkata" },
  "bangalore": { name: "Bengaluru", country: "IN", timeZone: "Asia/Kolkata" },
  "bengaluru": { name: "Bengaluru", country: "IN", timeZone: "Asia/Kolkata" },
  "kolkata": { name: "Kolkata", country: "IN", timeZone: "Asia/Kolkata" },
  "hyderabad": { name: "Hyderabad", country: "IN", timeZone: "Asia/Kolkata" },
  "chennai": { name: "Chennai", country: "IN", timeZone: "Asia/Kolkata" },
  "india": { name: "India", country: "IN", timeZone: "Asia/Kolkata" },
  "karachi": { name: "Karachi", country: "PK", timeZone: "Asia/Karachi" },
  "lahore": { name: "Lahore", country: "PK", timeZone: "Asia/Karachi" },
  "islamabad": { name: "Islamabad", country: "PK", timeZone: "Asia/Karachi" },
  "colombo": { name: "Colombo", country: "LK", timeZone: "Asia/Colombo" },
  "kathmandu": { name: "Kathmandu", country: "NP", timeZone: "Asia/Kathmandu" },
  "singapore": { name: "Singapore", country: "SG", timeZone: "Asia/Singapore" },
  "sg": { name: "Singapore", country: "SG", timeZone: "Asia/Singapore" },
  "sgp": { name: "Singapore", country: "SG", timeZone: "Asia/Singapore" },
  "kuala lumpur": { name: "Kuala Lumpur", country: "MY", timeZone: "Asia/Kuala_Lumpur" },
  "kl": { name: "Kuala Lumpur", country: "MY", timeZone: "Asia/Kuala_Lumpur" },
  "bangkok": { name: "Bangkok", country: "TH", timeZone: "Asia/Bangkok" },
  "jakarta": { name: "Jakarta", country: "ID", timeZone: "Asia/Jakarta" },
  "bali": { name: "Bali", country: "ID", timeZone: "Asia/Makassar" },
  "manila": { name: "Manila", country: "PH", timeZone: "Asia/Manila" },
  "ho chi minh": { name: "Ho Chi Minh City", country: "VN", timeZone: "Asia/Ho_Chi_Minh" },
  "hanoi": { name: "Hanoi", country: "VN", timeZone: "Asia/Ho_Chi_Minh" },
  "tokyo": { name: "Tokyo", country: "JP", timeZone: "Asia/Tokyo" },
  "tyo": { name: "Tokyo", country: "JP", timeZone: "Asia/Tokyo" },
  "japan": { name: "Tokyo", country: "JP", timeZone: "Asia/Tokyo" },
  "osaka": { name: "Osaka", country: "JP", timeZone: "Asia/Tokyo" },
  "seoul": { name: "Seoul", country: "KR", timeZone: "Asia/Seoul" },
  "korea": { name: "Seoul", country: "KR", timeZone: "Asia/Seoul" },
  "hong kong": { name: "Hong Kong", country: "HK", timeZone: "Asia/Hong_Kong" },
  "hk": { name: "Hong Kong", country: "HK", timeZone: "Asia/Hong_Kong" },
  "taipei": { name: "Taipei", country: "TW", timeZone: "Asia/Taipei" },
  "taiwan": { name: "Taipei", country: "TW", timeZone: "Asia/Taipei" },
  "shanghai": { name: "Shanghai", country: "CN", timeZone: "Asia/Shanghai" },
  "beijing": { name: "Beijing", country: "CN", timeZone: "Asia/Shanghai" },
  "china": { name: "Beijing", country: "CN", timeZone: "Asia/Shanghai" },

  // Australia & Pacific
  "sydney": { name: "Sydney", country: "AU", timeZone: "Australia/Sydney" },
  "melbourne": { name: "Melbourne", country: "AU", timeZone: "Australia/Melbourne" },
  "brisbane": { name: "Brisbane", country: "AU", timeZone: "Australia/Brisbane" },
  "perth": { name: "Perth", country: "AU", timeZone: "Australia/Perth" },
  "adelaide": { name: "Adelaide", country: "AU", timeZone: "Australia/Adelaide" },
  "auckland": { name: "Auckland", country: "NZ", timeZone: "Pacific/Auckland" },
  "wellington": { name: "Wellington", country: "NZ", timeZone: "Pacific/Auckland" },

  // South America
  "sao paulo": { name: "São Paulo", country: "BR", timeZone: "America/Sao_Paulo" },
  "rio": { name: "Rio de Janeiro", country: "BR", timeZone: "America/Sao_Paulo" },
  "buenos aires": { name: "Buenos Aires", country: "AR", timeZone: "America/Argentina/Buenos_Aires" },
  "santiago": { name: "Santiago", country: "CL", timeZone: "America/Santiago" },
  "lima": { name: "Lima", country: "PE", timeZone: "America/Lima" },
  "bogota": { name: "Bogota", country: "CO", timeZone: "America/Bogota" },

  // Standard Timezone Acronyms / Direct Names
  "utc": { name: "UTC", country: "", timeZone: "UTC" },
  "gmt": { name: "GMT", country: "", timeZone: "UTC" },
  "est": { name: "EST (US Eastern)", country: "US", timeZone: "America/New_York" },
  "edt": { name: "EDT (US Eastern)", country: "US", timeZone: "America/New_York" },
  "et": { name: "ET (US Eastern)", country: "US", timeZone: "America/New_York" },
  "cst": { name: "CST (US Central)", country: "US", timeZone: "America/Chicago" },
  "cdt": { name: "CDT (US Central)", country: "US", timeZone: "America/Chicago" },
  "ct": { name: "CT (US Central)", country: "US", timeZone: "America/Chicago" },
  "mst": { name: "MST (US Mountain)", country: "US", timeZone: "America/Denver" },
  "mdt": { name: "MDT (US Mountain)", country: "US", timeZone: "America/Denver" },
  "mt": { name: "MT (US Mountain)", country: "US", timeZone: "America/Denver" },
  "pst": { name: "PST (US Pacific)", country: "US", timeZone: "America/Los_Angeles" },
  "pdt": { name: "PDT (US Pacific)", country: "US", timeZone: "America/Los_Angeles" },
  "pt": { name: "PT (US Pacific)", country: "US", timeZone: "America/Los_Angeles" },
  "cet": { name: "CET (Central European)", country: "EU", timeZone: "Europe/Paris" },
  "cest": { name: "CEST (Central European Summer)", country: "EU", timeZone: "Europe/Paris" },
  "bst": { name: "BST (British Summer)", country: "UK", timeZone: "Europe/London" },
  "jst": { name: "JST (Japan Standard)", country: "JP", timeZone: "Asia/Tokyo" },
  "ist": { name: "IST (India Standard)", country: "IN", timeZone: "Asia/Kolkata" },
  "aest": { name: "AEST (Australian Eastern)", country: "AU", timeZone: "Australia/Sydney" },
  "aedt": { name: "AEDT (Australian Eastern Daylight)", country: "AU", timeZone: "Australia/Sydney" },
};
